-- =====================================================
-- SUBCATEGORIES TABLE CREATION SCRIPT FOR SUPABASE
-- =====================================================
-- 
-- Ovaj SQL kod kreira tabelu 'subcategories' u Supabase bazi
-- Tabela je povezana s 'categories' tabelom putem foreign key-a
--
-- UPUTE ZA POKRETANJE:
-- 1. Idite u Supabase dashboard
-- 2. Otvorite SQL Editor
-- 3. Kopirajte i zalijepite ovaj kod
-- 4. Kliknite "Run" da izvršite
-- =====================================================

-- 1. KREIRANJE SUBCATEGORIES TABELE
-- ==================================
CREATE TABLE IF NOT EXISTS public.subcategories (
    -- Osnovni ID (primary key)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Ime podkategorije (obavezno, jedinstveno)
    name TEXT NOT NULL,
    
    -- Opis podkategorije (opcionalno)
    description TEXT,
    
    -- URL slug za SEO (automatski generirano iz imena)
    slug TEXT UNIQUE,
    
    -- URL slike podkategorije (opcionalno)
    image TEXT,
    
    -- Foreign key poveznica na categories tabelu (obavezno)
    category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    
    -- Broj proizvoda u ovoj podkategoriji (cache vrijednost)
    product_count INTEGER DEFAULT 0,
    
    -- Timestamp kreiranje/ažuriranje zapisa
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- Constraint: ime mora biti jedinstveno unutar kategorije
    UNIQUE(name, category_id)
);

-- 2. KREIRANJE INDEKSA ZA OPTIMIZACIJU
-- ====================================

-- Index za brže pretrage po kategoriji
CREATE INDEX IF NOT EXISTS idx_subcategories_category_id 
ON public.subcategories(category_id);

-- Index za pretrage po imenu
CREATE INDEX IF NOT EXISTS idx_subcategories_name 
ON public.subcategories(name);

-- Index za pretrage po slug-u
CREATE INDEX IF NOT EXISTS idx_subcategories_slug 
ON public.subcategories(slug);

-- Composite index za sortiranje po kategoriji i imenu
CREATE INDEX IF NOT EXISTS idx_subcategories_category_name 
ON public.subcategories(category_id, name);

-- 3. KREIRANJE TRIGGER FUNKCIJE ZA AUTO-UPDATE
-- ============================================

-- Funkcija za automatsko ažuriranje updated_at polja
CREATE OR REPLACE FUNCTION update_subcategories_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger koji automatski ažurira updated_at prilikom UPDATE-a
CREATE TRIGGER trigger_update_subcategories_updated_at
    BEFORE UPDATE ON public.subcategories
    FOR EACH ROW
    EXECUTE FUNCTION update_subcategories_updated_at();

-- 4. KREIRANJE FUNKCIJE ZA AUTO-GENERIRANJE SLUG-A
-- ================================================

-- Funkcija za kreiranje slug-a iz imena
CREATE OR REPLACE FUNCTION generate_subcategory_slug()
RETURNS TRIGGER AS $$
BEGIN
    -- Ako slug nije postavljen, generiraj ga iz imena
    IF NEW.slug IS NULL OR NEW.slug = '' THEN
        NEW.slug := LOWER(REGEXP_REPLACE(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(
                        REGEXP_REPLACE(NEW.name, '[čć]', 'c', 'g'),
                        '[žš]', 's', 'g'
                    ),
                    'đ', 'd', 'g'
                ),
                '[^a-zA-Z0-9\s-]', '', 'g'
            ),
            '\s+', '-', 'g'
        ));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger za automatsko generiranje slug-a
CREATE TRIGGER trigger_generate_subcategory_slug
    BEFORE INSERT OR UPDATE ON public.subcategories
    FOR EACH ROW
    EXECUTE FUNCTION generate_subcategory_slug();

-- 5. ROW LEVEL SECURITY (RLS) POSTAVKE
-- ====================================

-- Omogući RLS za subcategories tabelu
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- Policy za javno čitanje (svi mogu čitati)
CREATE POLICY "Subcategories are viewable by everyone" ON public.subcategories
    FOR SELECT USING (true);

-- Policy za dodavanje (samo autentificirani korisnici)
CREATE POLICY "Subcategories can be inserted by authenticated users" ON public.subcategories
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Policy za ažuriranje (samo autentificirani korisnici)
CREATE POLICY "Subcategories can be updated by authenticated users" ON public.subcategories
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Policy za brisanje (samo autentificirani korisnici)
CREATE POLICY "Subcategories can be deleted by authenticated users" ON public.subcategories
    FOR DELETE USING (auth.role() = 'authenticated');

-- 6. DODAVANJE OSNOVNIH PODKATEGORIJA (PRIMJERI)
-- ==============================================

-- Dodaj osnovne podkategorije za "Bijela tehnika" (pretpostavljamo da je category_id = 1)
INSERT INTO public.subcategories (name, description, category_id, image) VALUES
    ('Perilice rublja', 'Perilice za rublje različitih kapaciteta i funkcionalnosti', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/perilice-rublja.jpg'),
    
    ('Sušilice rublja', 'Sušilice za rublje i kombiniranih uređaja', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/susilice-rublja.jpg'),
    
    ('Hladnjaci', 'Hladnjaci različitih veličina i tipova hlađenja', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/hladnjaci.jpg'),
    
    ('Frižideri', 'Zamrzivači i kombiniranih hladnjak-zamrzivač uređaja', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/frizideri.jpg'),
    
    ('Perilice posuđa', 'Perilice za posuđe različitih veličina i programa', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/perilice-posuda.jpg'),
    
    ('Pećnice i štednjaci', 'Električni i plinski štednjaci, ugradbene pećnice', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/pecnice-stednjaci.jpg'),
    
    ('Nape i aspiratori', 'Kuhinjske nape i ventilacijski sustavi', 
     (SELECT id FROM public.categories WHERE name = 'Bijela tehnika' LIMIT 1), 
     '/images/subcategories/nape-aspiratori.jpg')

ON CONFLICT (name, category_id) DO NOTHING;

-- Dodaj podkategorije za "Mobiles" kategoriju ako postoji
INSERT INTO public.subcategories (name, description, category_id, image) VALUES
    ('Smartphones', 'Pametni telefoni svih brandova i cijenskih kategorija', 
     (SELECT id FROM public.categories WHERE name = 'Mobiles' LIMIT 1), 
     '/images/subcategories/smartphones.jpg'),
    
    ('Tablets', 'Tableti za rad, zabavu i kreativnost', 
     (SELECT id FROM public.categories WHERE name = 'Mobiles' LIMIT 1), 
     '/images/subcategories/tablets.jpg'),
    
    ('Oprema i dodaci', 'Maske, stakla, punjači i ostala oprema za mobitele', 
     (SELECT id FROM public.categories WHERE name = 'Mobiles' LIMIT 1), 
     '/images/subcategories/oprema-dodaci.jpg')

ON CONFLICT (name, category_id) DO NOTHING;

-- 7. KREIRANJE FUNKCIJE ZA AŽURIRANJE PRODUCT_COUNT
-- =================================================

-- Funkcija za ažuriranje brojača proizvoda u podkategoriji
CREATE OR REPLACE FUNCTION update_subcategory_product_count(subcategory_id_param BIGINT)
RETURNS INTEGER AS $$
DECLARE
    product_count INTEGER;
BEGIN
    -- Prebroji proizvode u podkategoriji
    SELECT COUNT(*) INTO product_count
    FROM public.products
    WHERE subcategory_id = subcategory_id_param;
    
    -- Ažuriraj product_count u subcategories tabeli
    UPDATE public.subcategories
    SET product_count = product_count,
        updated_at = TIMEZONE('utc'::text, NOW())
    WHERE id = subcategory_id_param;
    
    RETURN product_count;
END;
$$ LANGUAGE plpgsql;

-- Funkcija za ažuriranje svih product_count u subcategories tabeli
CREATE OR REPLACE FUNCTION refresh_all_subcategory_counts()
RETURNS INTEGER AS $$
DECLARE
    updated_count INTEGER := 0;
    subcategory_record RECORD;
BEGIN
    -- Prođi kroz sve podkategorije i ažuriraj brojače
    FOR subcategory_record IN SELECT id FROM public.subcategories LOOP
        PERFORM update_subcategory_product_count(subcategory_record.id);
        updated_count := updated_count + 1;
    END LOOP;
    
    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;

-- 8. DODAVANJE FOREIGN KEY U PRODUCTS TABELU (AKO NE POSTOJI)
-- ===========================================================

-- Dodaj subcategory_id kolonu u products tabelu ako ne postoji
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'products' 
        AND column_name = 'subcategory_id'
        AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.products 
        ADD COLUMN subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL;
        
        -- Dodaj index za optimizaciju
        CREATE INDEX idx_products_subcategory_id ON public.products(subcategory_id);
    END IF;
END $$;

-- 9. KREIRANJE VIEW-A ZA LAKŠE DOHVAĆANJE PODATAKA
-- ================================================

-- View koji kombinira podkategorije s njihovim kategorijama
CREATE OR REPLACE VIEW public.subcategories_with_category AS
SELECT 
    s.id,
    s.name,
    s.description,
    s.slug,
    s.image,
    s.category_id,
    s.product_count,
    s.created_at,
    s.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    c.description AS category_description
FROM public.subcategories s
LEFT JOIN public.categories c ON s.category_id = c.id
ORDER BY c.name, s.name;

-- 10. ZAVRŠNE PORUKE
-- ==================

-- Provjeri da li je tabela uspješno kreirana
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'subcategories' AND table_schema = 'public') THEN
        RAISE NOTICE '✅ Subcategories tabela je uspješno kreirana!';
        RAISE NOTICE '📋 Dostupne funkcije:';
        RAISE NOTICE '   - update_subcategory_product_count(id)';
        RAISE NOTICE '   - refresh_all_subcategory_counts()';
        RAISE NOTICE '🔍 Dostupni view-ovi:';
        RAISE NOTICE '   - subcategories_with_category';
        RAISE NOTICE '🎯 Tabela je spremna za korištenje s API rutama!';
    ELSE
        RAISE NOTICE '❌ Greška pri kreiranju subcategories tabele!';
    END IF;
END $$;

-- KRAJ SKRIPTE
-- ============ 