-- =====================================================
-- SUBCATEGORIES TABLE FIX - Mobili Più
-- =====================================================
-- Ovaj kod će riješiti problem s podkategorijama
-- =====================================================

-- 1. UKLONI POSTOJEĆE PROBLEMATIČNE PODATKE AKO POSTOJE
DROP TABLE IF EXISTS public.subcategories CASCADE;

-- 2. KREIRAJ SUBCATEGORIES TABELU IZNOVA
CREATE TABLE public.subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    slug TEXT UNIQUE,
    image TEXT,
    category_id BIGINT NOT NULL,
    product_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- Foreign key constraint na categories tabelu
    CONSTRAINT fk_subcategories_category 
        FOREIGN KEY (category_id) 
        REFERENCES public.categories(id) 
        ON DELETE CASCADE,
    
    -- Jedinstveno ime po kategoriji
    UNIQUE(name, category_id)
);

-- 3. KREIRAJ INDEKSE
CREATE INDEX idx_subcategories_category_id ON public.subcategories(category_id);
CREATE INDEX idx_subcategories_name ON public.subcategories(name);
CREATE INDEX idx_subcategories_slug ON public.subcategories(slug);

-- 4. OMOGUĆI RLS
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;

-- 5. KREIRAJ RLS POLICY
CREATE POLICY "Subcategories are viewable by everyone" ON public.subcategories
    FOR SELECT USING (true);

CREATE POLICY "Subcategories can be inserted by authenticated users" ON public.subcategories
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Subcategories can be updated by authenticated users" ON public.subcategories
    FOR UPDATE USING (true);

CREATE POLICY "Subcategories can be deleted by authenticated users" ON public.subcategories
    FOR DELETE USING (true);

-- 6. PROVJERI I DODAJ POSTOJEĆE KATEGORIJE AKO NE POSTOJE
INSERT INTO public.categories (name, subcategories) VALUES
('Bijela tehnika', '["Hladnjaci", "Perilice rublja", "Sušilice rublja", "Perilice posuđa", "Štednjaci", "Pećnice", "Frižideri"]'),
('Mobiles', '["Smartphones", "Tablets", "Oprema i dodaci"]'),
('Mali kućanski aparati', '["Kava aparati", "Toster", "Blender", "Mikser", "Friteza"]')
ON CONFLICT (name) DO NOTHING;

-- 7. DODAJ PODKATEGORIJE ZA BIJELU TEHNIKU
INSERT INTO public.subcategories (name, description, category_id, slug, image) 
SELECT 
    subcategory_name,
    'Podkategorija: ' || subcategory_name,
    c.id,
    LOWER(REGEXP_REPLACE(
        REGEXP_REPLACE(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    REGEXP_REPLACE(subcategory_name, '[čć]', 'c', 'g'),
                    '[žš]', 's', 'g'
                ),
                'đ', 'd', 'g'
            ),
            '[^a-zA-Z0-9\s-]', '', 'g'
        ),
        '\s+', '-', 'g'
    )),
    '/images/subcategories/' || LOWER(REGEXP_REPLACE(subcategory_name, '\s+', '-', 'g')) || '.jpg'
FROM (
    VALUES 
        ('Perilice rublja'),
        ('Sušilice rublja'), 
        ('Hladnjaci'),
        ('Frižideri'),
        ('Perilice posuđa'),
        ('Pećnice i štednjaci'),
        ('Nape i aspiratori'),
        ('Mikrovalne pećnice'),
        ('Zamrzivači')
) AS subcats(subcategory_name)
CROSS JOIN public.categories c
WHERE c.name = 'Bijela tehnika'
ON CONFLICT (name, category_id) DO NOTHING;

-- 8. DODAJ PODKATEGORIJE ZA MOBILES
INSERT INTO public.subcategories (name, description, category_id, slug, image) 
SELECT 
    subcategory_name,
    'Podkategorija: ' || subcategory_name,
    c.id,
    LOWER(REGEXP_REPLACE(subcategory_name, '\s+', '-', 'g')),
    '/images/subcategories/' || LOWER(REGEXP_REPLACE(subcategory_name, '\s+', '-', 'g')) || '.jpg'
FROM (
    VALUES 
        ('Smartphones'),
        ('Tablets'),
        ('Oprema i dodaci')
) AS subcats(subcategory_name)
CROSS JOIN public.categories c
WHERE c.name = 'Mobiles'
ON CONFLICT (name, category_id) DO NOTHING;

-- 9. DODAJ PODKATEGORIJE ZA MALI KUĆANSKI APARATI
INSERT INTO public.subcategories (name, description, category_id, slug, image) 
SELECT 
    subcategory_name,
    'Podkategorija: ' || subcategory_name,
    c.id,
    LOWER(REGEXP_REPLACE(subcategory_name, '\s+', '-', 'g')),
    '/images/subcategories/' || LOWER(REGEXP_REPLACE(subcategory_name, '\s+', '-', 'g')) || '.jpg'
FROM (
    VALUES 
        ('Kava aparati'),
        ('Toster'),
        ('Blender'),
        ('Mikser'),
        ('Friteza'),
        ('Grill'),
        ('Robot za kuhinju')
) AS subcats(subcategory_name)
CROSS JOIN public.categories c
WHERE c.name = 'Mali kućanski aparati'
ON CONFLICT (name, category_id) DO NOTHING;

-- 10. DODAJ SUBCATEGORY_ID KOLONU U PRODUCTS TABELU AKO NE POSTOJI
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'products' 
        AND column_name = 'subcategory_id'
        AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.products 
        ADD COLUMN subcategory_id BIGINT 
        REFERENCES public.subcategories(id) ON DELETE SET NULL;
        
        CREATE INDEX idx_products_subcategory_id ON public.products(subcategory_id);
    END IF;
END $$;

-- 11. AŽURIRAJ PRODUCT_COUNT U SUBCATEGORIES
UPDATE public.subcategories 
SET product_count = (
    SELECT COUNT(*) 
    FROM public.products p 
    WHERE p.subcategory = subcategories.name
);

-- 12. KREIRAJ TRIGGER ZA AUTO-UPDATE UPDATED_AT
CREATE OR REPLACE FUNCTION update_subcategories_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_subcategories_updated_at
    BEFORE UPDATE ON public.subcategories
    FOR EACH ROW
    EXECUTE FUNCTION update_subcategories_updated_at();

-- 13. ZAVRŠNA PROVJERA
DO $$
BEGIN
    RAISE NOTICE '✅ Subcategories tabela je uspješno kreirana!';
    RAISE NOTICE '📊 Ukupno kategorija: %', (SELECT COUNT(*) FROM public.categories);
    RAISE NOTICE '📊 Ukupno podkategorija: %', (SELECT COUNT(*) FROM public.subcategories);
    RAISE NOTICE '🎯 Tabela je spremna za korištenje!';
END $$;

-- KONAC SKRIPTE 